name: Purge jsDelivr CDN Cache
on:
  push:
    branches: [ main ]
    paths:
      - "s.js"
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Edge CDN
        run: |
          curl -s -S -X POST https://purge.jsdelivr.net/ \
            -H "Content-Type: application/json" \
            -d '{"path":["/gh/wyattberrystapperp/TizenCobalt@main/s.js","/gh/wyattberrystapperp/TizenCobalt/s.js"]}'
